export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_DOCTOR = "GET_DOCTOR"
export const LOADING_DOCTOR = "LOADING_DOCTOR"

export const DOCTOR_ERROES = "DOCTOR_ERROES"
export const ADD_DOCTOR = "ADD_DOCTOR"

export const REMOVE_DOCTOR = "REMOVE_DOCTOR"
export const UPDATAS_DOCTOR = "UPDATAS_DOCTOR"




