export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_MEDICINES = "GET_MEDICINES"
export const LOADING_MEDICINES = "LOADING_MEDICINES"

export const MEDICINES_ERROES = "MEDICINES_ERROES"
export const ADD_MEDICINES = "ADD_MEDICINES"

export const REMOVE_MEDICINES = "REMOVE_MEDICINES"
export const UPDATAS_MEDICINES = "UPDATAS_MEDICINES"




